/*
 * [INPUT]: 依赖 lib/marketing-apps 独立营销数据源、marketing-site 的 App URL 上下文与 Next Link
 * [OUTPUT]: 对外提供 recut.video/apps 的应用市场目录与 recut.video/apps/:appID 的公开 App SEO 落地页；每个 App 是可索引的 SEO 落地页，安装/使用引导到工作台
 * [POS]: web/components 的公开官网应用层；只展示 lib/marketing-apps 静态营销数据，不读取工作台 Catalog 或本地 service 安装状态
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
"use client";

import Link from "next/link";
import { marketingApps, type MarketingApp } from "@/lib/marketing-apps";
import { useMarketingAppURL } from "@/components/marketing-site";
import { trackEvent } from "@/components/posthog-analytics";

export function MarketingAppsContent() {
  return <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p className="font-mono text-[11px] font-semibold tracking-[0.18em] text-primary">RECUT APPS</p><h1 className="mt-4 text-4xl font-semibold tracking-tight">可扩展的创作能力。</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">每个 App 都是一类创作能力：用同一套本地工作台承载，可安装、可替换、也可以自己编写。以下页面可在应用市场与工作台中打开。</p><div className="mt-10 grid gap-4 md:grid-cols-2">{marketingApps.map((app) => <article className="flex min-h-56 flex-col rounded-2xl border bg-card p-6 transition hover:border-primary/35 hover:shadow-sm" key={app.id}><p className="font-mono text-[10px] font-semibold tracking-[0.15em] text-primary">{app.type === "project" ? "PROJECT APP" : "STANDALONE APP"}</p><h2 className="mt-4 text-xl font-semibold"><Link className="transition hover:text-primary" href={`/apps/${encodeURIComponent(app.id)}`}>{app.name}</Link></h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{app.tagline}</p><div className="mt-auto flex items-center justify-between gap-3 pt-6"><span className="text-xs text-muted-foreground">{app.type === "project" ? "项目型 App" : "工作区 App"}</span><Link className="inline-flex items-center gap-1 text-sm font-semibold text-primary" href={`/apps/${encodeURIComponent(app.id)}`}>了解 {app.name} →</Link></div>{app.requirements && <p className="mt-3 rounded-lg border border-warning/35 bg-warning/5 px-3 py-2 text-xs leading-5 text-muted-foreground">运行有设备与磁盘要求，请先阅读详情。</p>}</article>)}</div></section>;
}

export function MarketingAppDetailContent({ app }: { app: MarketingApp }) {
  const appURL = useMarketingAppURL();
  const detailURL = `${appURL}/apps/${encodeURIComponent(app.id)}`;
  const repoURL = app.repository?.replace(/\.git$/, "");
  const related = app.relatedApps.map((id) => marketingApps.find((item) => item.id === id)).filter((item): item is MarketingApp => Boolean(item));
  return <article className="mx-auto max-w-3xl px-5 py-16 sm:px-8"><Link className="text-sm font-semibold text-primary" href="/apps">← 所有应用</Link><p className="mt-10 font-mono text-xs text-muted-foreground">{app.type === "project" ? "项目型 App" : "工作区 App"}</p><h1 className="mt-4 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">{app.name}</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">{app.tagline}</p><div className="mt-10 space-y-6 border-t pt-8 text-base leading-8 text-foreground/85">{app.overview.map((paragraph, index) => <p className="mt-2" key={index}>{paragraph}</p>)}{app.sections.map(({ heading, body }) => <section key={heading}><h2 className="mt-12 text-2xl font-semibold tracking-tight">{heading}</h2>{body.map((paragraph, index) => <p className="mt-2" key={index}>{paragraph}</p>)}</section>)}<section><h2 className="mt-12 text-2xl font-semibold tracking-tight">{app.name}能帮你做什么</h2><ul className="mt-4 space-y-2">{app.highlights.map((item) => <li className="pl-1" key={item}>· {item}</li>)}</ul></section>{app.faq.length > 0 && <section><h2 className="mt-12 text-2xl font-semibold tracking-tight">常见问题</h2><div className="mt-4 space-y-4">{app.faq.map(({ question, answer }) => <div className="rounded-xl border bg-card p-5" key={question}><h3 className="text-base font-semibold">{question}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{answer}</p></div>)}</div></section>}{app.requirements && <div className="rounded-xl border border-warning/35 bg-warning/5 p-5"><h2 className="text-sm font-semibold">{app.requirements.title}</h2><ul className="mt-3 space-y-2">{app.requirements.items.map((item) => <li className="pl-1 text-sm leading-6 text-muted-foreground" key={item}>· {item}</li>)}</ul>{app.requirements.note && <p className="mt-3 text-xs leading-5 text-muted-foreground">{app.requirements.note}</p>}</div>}</div><div className="mt-10 flex flex-wrap gap-3"><a className="inline-flex h-11 items-center rounded-lg bg-primary px-5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/85" href={detailURL} onClick={() => trackEvent("recut_workspace_clicked", { location: "app_detail", app_id: app.id })}>在工作台打开 {app.name} ↗</a>{repoURL && <a className="inline-flex h-11 items-center rounded-lg border bg-card px-5 text-sm font-semibold transition hover:bg-muted" href={repoURL} onClick={() => trackEvent("recut_external_clicked", { target: "app_repo", app_id: app.id })} rel="noreferrer" target="_blank">查看源码</a>}</div>{related.length > 0 && <div className="mt-10 border-t pt-8"><h2 className="text-sm font-semibold">继续了解</h2><div className="mt-3 flex flex-wrap gap-2">{related.map((item) => <Link className="inline-flex items-center gap-1 rounded-lg border bg-card px-3 py-2 text-sm font-medium text-muted-foreground transition hover:border-primary/35 hover:text-foreground" href={`/apps/${encodeURIComponent(item.id)}`} key={item.id}>{item.name} →</Link>)}</div></div>}</article>;
}
