/*
 * [INPUT]: 依赖项目范围 Agent Session/Media HTTP API、SSE 与基础 UI 原子组件
 * [OUTPUT]: 对外提供带输入法保护、图片上传/粘贴上下文、Codex 模型/推理强度配置与时间线预览的 ProjectAgentPanel；工具调用以行内卡片展示输入、输出/错误与耗时
 * [POS]: components 的通用 Agent 侧栏；运行期间的用户消息持久化排队，每张图片以资产引用绑定到对应用户 Turn
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
"use client";

import { ArrowUp, Bot, ChevronDown, ChevronRight, CircleStop, Copy, History, ImagePlus, MessageSquarePlus, SlidersHorizontal, ThumbsDown, ThumbsUp, X } from "lucide-react";
import { FormEvent, type ClipboardEvent, type ReactNode, useEffect, useRef, useState } from "react";

import { AgentMessageContent } from "@/components/agent-message-content";
import { Button } from "@/components/ui/button";

type Session = { id: string; title: string; runtime: string; status: string; updatedAt: string; projectName?: string; appId?: string; codexModel?: string; reasoningEffort?: string };
type CodexConfiguration = { codexModel: string; reasoningEffort: string };
const defaultCodexConfiguration: CodexConfiguration = { codexModel: "gpt-5.6-terra", reasoningEffort: "xhigh" };
type Attachment = { assetId: string; name: string; mimeType: string };
type UploadedAsset = { id: string; name: string; mimeType: string };
type Turn = { id: string; role: "user" | "assistant"; content: string; status: string; createdAt: string; attachments?: Attachment[] };
type ToolPayload = { label?: string; phase?: string; toolCallId?: string; tool?: string; toolName?: string; detail?: string };
type AgentEvent = { id: number; turnId?: string; type: string; createdAt: string; payload?: ToolPayload };
type Detail = Session & { turns: Turn[]; events: AgentEvent[]; lastEventId: number };
type Props = { apiBase: string; online: boolean; projectID: string | null };

export function ProjectAgentPanel({ apiBase, online, projectID }: Props) {
  const [sessions, setSessions] = useState<Session[]>([]); const [activeID, setActiveID] = useState<string | null>(null); const [detail, setDetail] = useState<Detail | null>(null); const [content, setContent] = useState(""); const [attachments, setAttachments] = useState<Attachment[]>([]); const [uploading, setUploading] = useState(false); const [error, setError] = useState(""); const [stopNotice, setStopNotice] = useState(""); const [historyOpen, setHistoryOpen] = useState(false); const [runtimeOpen, setRuntimeOpen] = useState(false); const [now, setNow] = useState(() => Date.now());
  const streamRef = useRef<EventSource | null>(null); const messagesRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (online && projectID) void loadSessions(); else { streamRef.current?.close(); setSessions([]); setDetail(null); setActiveID(null); } }, [online, projectID]);
  useEffect(() => () => streamRef.current?.close(), []); useEffect(() => { messagesRef.current?.scrollTo({ top: messagesRef.current.scrollHeight, behavior: "smooth" }); }, [detail?.turns.length, detail?.events.length]); useEffect(() => { if (detail?.status !== "running") return; setNow(Date.now()); const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [detail?.status]);
  async function loadSessions() { if (!projectID) return; const response = await fetch(`${apiBase}/v1/agent-sessions?projectId=${encodeURIComponent(projectID)}`); if (!response.ok) return; const next: Session[] = await response.json(); setSessions(next); const selected = activeID && next.some((session) => session.id === activeID) ? activeID : next[0]?.id ?? null; if (selected) await open(selected); }
  async function open(id: string) { streamRef.current?.close(); setActiveID(id); const response = await fetch(`${apiBase}/v1/agent-sessions/${id}`); if (!response.ok) { setError("无法读取对话"); return; } const next: Detail = await response.json(); setDetail(next); const stream = new EventSource(`${apiBase}/v1/agent-sessions/${id}/events?after=${next.lastEventId}`); stream.addEventListener("agent", (event) => { const incoming = JSON.parse((event as MessageEvent<string>).data) as AgentEvent; setDetail((current) => current ? { ...current, status: incoming.type === "turn.started" ? "running" : current.status, events: [...current.events, incoming], lastEventId: incoming.id } : current); if (incoming.type === "turn.cancelled") setStopNotice("已停止当前回复"); if (incoming.type === "turn.started") setStopNotice(""); if (["assistant.completed", "turn.completed", "turn.failed", "turn.cancelled", "session.updated"].includes(incoming.type)) void refresh(id); }); streamRef.current = stream; }
  async function refresh(id: string) { const response = await fetch(`${apiBase}/v1/agent-sessions/${id}`); if (!response.ok) return; const next: Detail = await response.json(); setDetail(next); setSessions((current) => [next, ...current.filter((session) => session.id !== id)]); }
  async function create(runtime: "codex" | "claude", configuration?: CodexConfiguration) { if (!projectID) return; setError(""); const response = await fetch(`${apiBase}/v1/agent-sessions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId: projectID, runtime, ...configuration }) }); if (!response.ok) { setError("无法创建对话"); return; } const session: Session = await response.json(); setSessions((current) => [session, ...current]); await open(session.id); }
  async function uploadImages(files: FileList | File[]) { if (!projectID) return; const images = [...files].filter((file) => file.type.startsWith("image/")); if (!images.length) return; setUploading(true); setError(""); try { const uploaded = await Promise.all(images.map(async (file) => { const body = new FormData(); body.append("file", file); const response = await fetch(`${apiBase}/v1/media/assets`, { method: "POST", body }); if (!response.ok) throw new Error("图片上传失败"); const asset: UploadedAsset = await response.json(); const attached = await fetch(`${apiBase}/v1/media/assets/${asset.id}/attach`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId: projectID }) }); if (!attached.ok) throw new Error("图片无法加入当前项目"); return { assetId: asset.id, name: asset.name, mimeType: asset.mimeType }; })); setAttachments((current) => [...current, ...uploaded.filter((item) => !current.some((existing) => existing.assetId === item.assetId))]); } catch (cause) { setError(cause instanceof Error ? cause.message : "图片上传失败"); } finally { setUploading(false); } }
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!activeID || (!content.trim() && !attachments.length)) return; const text = content.trim(); const pendingAttachments = attachments; setContent(""); setAttachments([]); setError(""); setStopNotice(""); const response = await fetch(`${apiBase}/v1/agent-sessions/${activeID}/turns`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: text, assetIds: pendingAttachments.map((attachment) => attachment.assetId) }) }); if (!response.ok) { setContent(text); setAttachments(pendingAttachments); setError("无法发送消息"); return; } await refresh(activeID); }
  async function stop() { if (!activeID) return; setStopNotice("正在停止当前回复…"); setDetail((current) => current ? { ...current, status: "stopping" } : current); const response = await fetch(`${apiBase}/v1/agent-sessions/${activeID}/stop`, { method: "POST" }); if (!response.ok) { setStopNotice(""); setError("无法停止当前回复"); await refresh(activeID); return; } await refresh(activeID); }
  if (!online) return <aside className="h-full overflow-y-auto bg-muted/40 p-4"><p className="text-xs font-medium">Agent 暂不可用</p><p className="mt-1 text-xs leading-5 text-muted-foreground">本地服务恢复后，会话与记录会自动回到这里。</p></aside>;
  return <aside className="relative flex h-full min-h-0 flex-col overflow-hidden bg-background"><header className="flex h-10 shrink-0 items-center justify-between border-b bg-card px-4"><p className="text-xs font-semibold tracking-wide">AI</p><div className="flex items-center gap-1"><Button className="size-7 px-0" onClick={() => { setRuntimeOpen(false); setHistoryOpen((value) => !value); }} title="会话历史" type="button" variant="ghost"><History className="size-3.5" /></Button><Button className="size-7 px-0" onClick={() => { setHistoryOpen(false); setRuntimeOpen((value) => !value); }} title="新建对话" type="button" variant="ghost"><MessageSquarePlus className="size-3.5" /></Button></div></header>{runtimeOpen && <RuntimePicker onChoose={(runtime, configuration) => { setRuntimeOpen(false); void create(runtime, configuration); }} />}{historyOpen && <SessionHistory activeID={activeID} onOpen={(id) => { setHistoryOpen(false); void open(id); }} sessions={sessions} />}<div className="min-h-0 flex-1 overflow-y-auto px-4 py-6 pb-36" ref={messagesRef}>{error && <p className="mb-4 text-xs text-destructive">{error}</p>}{stopNotice && <p className="mb-4 text-xs text-muted-foreground">{stopNotice}</p>}{!detail ? <EmptyAgent onCreate={() => setRuntimeOpen(true)} /> : <Conversation apiBase={apiBase} detail={detail} now={now} />}</div><Composer apiBase={apiBase} attachments={attachments} content={content} disabled={!detail} onChange={setContent} onRemoveAttachment={(assetID) => setAttachments((current) => current.filter((attachment) => attachment.assetId !== assetID))} onSend={send} onStop={() => void stop()} onUpload={uploadImages} running={detail?.status === "running" || detail?.status === "stopping"} stopping={detail?.status === "stopping"} uploading={uploading} /></aside>;
}

type TimelineItem = { id: string; at: string; kind: "user"; turn: Turn } | { id: string; at: string; kind: "assistant"; turn: Turn } | { id: string; at: string; kind: "tool"; call: ToolCall };
type ToolCall = { id: string; createdAt: string; completedAt?: string; state: "running" | "success" | "error"; input?: string; output?: string; error?: string; payload: ToolPayload };

function Conversation({ apiBase, detail, now }: { apiBase: string; detail: Detail; now: number }) {
  const turnItems: TimelineItem[] = detail.turns.map((turn) => turn.role === "user" ? { id: turn.id, at: turn.createdAt, kind: "user", turn } : { id: turn.id, at: turn.createdAt, kind: "assistant", turn });
  const timeline: TimelineItem[] = [...turnItems, ...toolCalls(detail.events).map((call) => ({ id: call.id, at: call.createdAt, kind: "tool", call }) as TimelineItem)].sort((left, right) => new Date(left.at).getTime() - new Date(right.at).getTime());
  const groups = responseGroups(timeline);
  const isProcessing = detail.status === "running" || detail.status === "stopping";
  return <div className="space-y-5">{groups.map((group) => <section key={group.id}>{group.user && <div className="ml-auto w-fit max-w-[85%]">{(group.user.attachments ?? []).map((attachment) => <img alt={attachment.name} className="mb-1 max-h-40 rounded-sm border object-cover" key={attachment.assetId} src={`${apiBase}/v1/media/assets/${attachment.assetId}/content`} />)}{group.user.content && <p className="rounded-sm bg-secondary px-3 py-2 text-left text-xs leading-5 break-words whitespace-pre-wrap">{group.user.content}</p>}{group.user.status === "queued" && <p className="mt-1 text-right text-[10px] text-muted-foreground">待发送</p>}</div>}<div className={group.user ? "mt-5 space-y-5" : "space-y-5"}>{group.items.map((item) => item.kind === "assistant" ? <AgentMessageContent apiBase={apiBase} content={item.turn.content} key={item.id} /> : <ToolTimelineItem call={item.call} key={item.id} now={now} />)}</div>{!isProcessing && group.items.some((item) => item.kind === "assistant") && <div className="mt-2 flex items-center gap-1 text-muted-foreground"><ActionIcon label="复制回复"><Copy /></ActionIcon><ActionIcon label="有帮助"><ThumbsUp /></ActionIcon><ActionIcon label="没帮助"><ThumbsDown /></ActionIcon></div>}</section>)}{detail.status === "running" && <RunningStatus events={detail.events} now={now} />}{detail.status === "stopping" && <p className="flex items-center gap-1.5 text-xs text-muted-foreground"><span className="size-1.5 animate-pulse rounded-full bg-warning" />正在停止当前回复…</p>}</div>;
}

type ResponseGroup = { id: string; user?: Turn; items: Exclude<TimelineItem, { kind: "user" }>[] };
function responseGroups(timeline: TimelineItem[]): ResponseGroup[] {
  const groups: ResponseGroup[] = []; let current: ResponseGroup | null = null;
  for (const item of timeline) { if (item.kind === "user") { current = { id: item.id, user: item.turn, items: [] }; groups.push(current); continue; } if (!current) { current = { id: "initial", items: [] }; groups.push(current); } current.items.push(item); }
  return groups;
}

function toolCalls(events: AgentEvent[]): ToolCall[] {
  const calls = new Map<string, ToolCall>();
  for (const event of events.filter((item) => item.type.startsWith("tool."))) {
    const id = `${event.turnId ?? "session"}:${event.payload?.toolCallId ?? event.id}`; const previous = calls.get(id);
    const call: ToolCall = { id, createdAt: previous?.createdAt ?? event.createdAt, completedAt: previous?.completedAt, state: previous?.state ?? "running", input: previous?.input, output: previous?.output, error: previous?.error, payload: { ...previous?.payload, ...event.payload } };
    if (event.type === "tool.started") call.input = event.payload?.detail;
    if (event.type === "tool.completed") { call.state = "success"; call.completedAt = event.createdAt; call.output = event.payload?.detail; }
    if (event.type === "tool.failed") { call.state = "error"; call.completedAt = event.createdAt; call.error = event.payload?.detail; }
    calls.set(id, call);
  }
  return [...calls.values()];
}

function ToolTimelineItem({ call, now }: { call: ToolCall; now: number }) {
  const [open, setOpen] = useState(false);
  const hasDetail = Boolean(call.input || call.output || call.error);
  const duration = toolDuration(call.createdAt, call.completedAt, now);
  const stateLabel = { running: "执行中", success: "已完成", error: "失败" }[call.state];
  const stateClass = { running: "animate-pulse bg-warning", success: "bg-success", error: "bg-destructive" }[call.state];
  const labelClass = call.state === "error" ? "text-destructive" : call.state === "success" ? "text-success" : "text-warning";
  return <div className="max-w-full text-[11px]">
    <div className="flex min-w-0 items-center gap-1.5 text-muted-foreground">
      <span className={`size-1.5 shrink-0 rounded-full ${stateClass}`} />
      <span className="truncate">{call.payload.label ?? "MCP 工具调用"}</span>
      {call.payload.toolName && <span className="truncate font-mono text-[10px] text-muted-foreground/80">{call.payload.toolName}</span>}
      <span className={`ml-auto shrink-0 text-[10px] ${labelClass}`}>{stateLabel} · {duration}</span>
      {hasDetail && <button aria-expanded={open} aria-label="展开工具调用详情" className="grid size-5 shrink-0 place-items-center rounded-sm hover:bg-muted hover:text-foreground" onClick={() => setOpen((value) => !value)} type="button"><ChevronRight className={`size-3 transition-transform ${open ? "rotate-90" : ""}`} /></button>}
    </div>
    {open && hasDetail && <div className={`mt-2 max-w-full rounded-sm border p-3 text-foreground ${call.state === "error" ? "border-destructive/40 bg-destructive/5" : "bg-muted/30"}`}>
      <div className="flex items-center justify-between gap-3"><p className="text-xs font-medium">{call.payload.label ?? "工具调用"}</p><span className={`shrink-0 text-[10px] ${labelClass}`}>{stateLabel} · 耗时 {duration}</span></div>
      {call.payload.toolName && <p className="mt-1 break-all font-mono text-[10px] text-muted-foreground">{call.payload.toolName}</p>}
      <ToolDetail title="调用参数" value={call.input} />
      <ToolDetail title={call.state === "error" ? "错误信息" : "执行结果"} value={call.error ?? call.output} />
    </div>}
  </div>;
}
function ToolDetail({ title, value }: { title: string; value?: string }) { return <section className="mt-3"><p className="mb-1 text-[10px] font-medium text-muted-foreground">{title}</p><pre className="max-h-56 overflow-auto whitespace-pre-wrap break-words rounded-sm bg-muted/60 p-2 font-mono text-[10px] leading-4">{value ? safeToolDetail(value) : "未返回数据"}</pre></section>; }
function toolDuration(startedAt: string, completedAt: string | undefined, now: number) { const elapsed = Math.max(0, (new Date(completedAt ?? now).getTime() - new Date(startedAt).getTime()) / 1000); return elapsed < 10 ? `${elapsed.toFixed(1)} 秒` : `${Math.round(elapsed)} 秒`; }
function safeToolDetail(value: string) { try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } }

function EmptyAgent({ onCreate }: { onCreate: () => void }) { return <div className="grid min-h-48 place-items-center text-center"><div><Bot className="mx-auto size-5 text-muted-foreground" /><p className="mt-2 text-xs font-medium">让 AI 协助这个项目</p><Button className="mt-3" onClick={onCreate} type="button" variant="outline">创建对话</Button></div></div>; }
function SessionHistory({ activeID, onOpen, sessions }: { activeID: string | null; onOpen: (id: string) => void; sessions: Session[] }) { return <section className="absolute right-3 top-14 z-20 w-[calc(100%-1.5rem)] overflow-hidden rounded-md border bg-popover shadow-[var(--shadow-overlay)]"><p className="border-b px-3 py-2 text-[10px] font-medium text-muted-foreground">此项目的会话历史</p><div className="max-h-64 overflow-y-auto p-1.5">{sessions.length === 0 ? <p className="px-2 py-5 text-center text-xs text-muted-foreground">还没有会话</p> : sessions.map((session) => <button className={`w-full rounded-sm px-2 py-2 text-left text-xs hover:bg-muted ${session.id === activeID ? "bg-accent" : ""}`} key={session.id} onClick={() => onOpen(session.id)} type="button"><span className="block truncate font-medium">{session.title}</span><span className="mt-0.5 block truncate text-[10px] text-muted-foreground">{session.runtime === "codex" ? `${codexModelLabel(session.codexModel)} · ${reasoningLabel(session.reasoningEffort)}` : "Claude Code"}</span></button>)}</div></section>; }
function Composer({ apiBase, attachments, content, disabled, onChange, onRemoveAttachment, onSend, onStop, onUpload, running, stopping, uploading }: { apiBase: string; attachments: Attachment[]; content: string; disabled: boolean; onChange: (value: string) => void; onRemoveAttachment: (assetID: string) => void; onSend: (event: FormEvent<HTMLFormElement>) => void; onStop: () => void; onUpload: (files: FileList | File[]) => void; running: boolean; stopping: boolean; uploading: boolean }) {
  const fileInput = useRef<HTMLInputElement>(null);
  const composing = useRef(false);
  function pasteImage(event: ClipboardEvent<HTMLTextAreaElement>) { const images = [...event.clipboardData.files].filter((file) => file.type.startsWith("image/")); if (images.length) { event.preventDefault(); onUpload(images); } }
  return <form className="absolute inset-x-0 bottom-0 border-t bg-card p-3" onSubmit={onSend}><div className="rounded-md border bg-popover px-3 py-2 shadow-[var(--shadow-overlay)]">{attachments.length > 0 && <div className="mb-2 flex flex-wrap gap-2">{attachments.map((attachment) => <div className="group relative size-14 overflow-hidden rounded-sm border bg-muted" key={attachment.assetId}><img alt={attachment.name} className="size-full object-cover" src={`${apiBase}/v1/media/assets/${attachment.assetId}/content`} /><button aria-label={`移除 ${attachment.name}`} className="absolute right-0.5 top-0.5 grid size-4 place-items-center rounded-full bg-background/90 text-foreground shadow-sm opacity-0 transition-opacity group-hover:opacity-100 focus:opacity-100" onClick={() => onRemoveAttachment(attachment.assetId)} type="button"><X className="size-3" /></button></div>)}</div>}<textarea className="block min-h-12 w-full resize-none bg-transparent py-0.5 text-xs leading-5 outline-none" disabled={disabled} onChange={(event) => onChange(event.target.value)} onCompositionEnd={() => { composing.current = false; }} onCompositionStart={() => { composing.current = true; }} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing && !composing.current) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} onPaste={pasteImage} placeholder="告诉 AI 需要做什么 — 可粘贴图片作为上下文" value={content} /><div className="mt-1 flex items-center justify-between"><div className="flex items-center gap-1 text-[10px] text-muted-foreground"><Bot className="size-3" />Agent <ChevronDown className="size-3" /><SlidersHorizontal className="ml-2 size-3.5" /></div><div className="flex items-center gap-1"><input accept="image/*" className="hidden" multiple onChange={(event) => { if (event.target.files) onUpload(event.target.files); event.currentTarget.value = ""; }} ref={fileInput} type="file" /><Button className="size-6 rounded-full p-0" disabled={disabled || uploading} onClick={() => fileInput.current?.click()} title="添加图片" type="button" variant="ghost"><ImagePlus className="size-3.5" /></Button>{running && !stopping && <Button className="size-6 rounded-full p-0" onClick={onStop} title="停止当前回复" type="button" variant="outline"><CircleStop className="size-3" /></Button>}<Button className="size-6 rounded-full p-0" disabled={disabled || uploading || (!content.trim() && !attachments.length)} title={running ? "加入待发送消息" : "发送"} type="submit"><ArrowUp className="size-3" /></Button></div></div></div></form>;
}
function RunningStatus({ events, now }: { events: AgentEvent[]; now: number }) { const started = [...events].reverse().find((event) => event.type === "turn.started"); const elapsed = started ? Math.max(0, Math.floor((now - new Date(started.createdAt).getTime()) / 1000)) : 0; return <p className="flex items-center gap-1.5 text-xs text-muted-foreground"><span className="size-1.5 animate-pulse rounded-full bg-success" />正在继续处理 · {elapsed}s</p>; }
function ActionIcon({ children, label }: { children: ReactNode; label: string }) { return <button aria-label={label} className="grid size-6 place-items-center rounded-sm hover:bg-muted hover:text-foreground [&>svg]:size-3" type="button">{children}</button>; }
function RuntimePicker({ onChoose }: { onChoose: (runtime: "codex" | "claude", configuration?: CodexConfiguration) => void }) { const [configuring, setConfiguring] = useState(false); const [configuration, setConfiguration] = useState(defaultCodexConfiguration); if (configuring) return <section className="absolute right-3 top-14 z-30 w-[calc(100%-1.5rem)] overflow-hidden rounded-md border bg-popover shadow-[var(--shadow-overlay)]"><div className="border-b px-3 py-2"><p className="text-xs font-medium">Codex 配置</p><p className="mt-0.5 text-[10px] text-muted-foreground">配置将固定在这次对话中。</p></div><label className="block px-3 pt-3 text-[10px] text-muted-foreground">模型<select className="mt-1.5 block w-full rounded-sm border bg-background px-2 py-2 text-xs text-foreground" onChange={(event) => setConfiguration((value) => ({ ...value, codexModel: event.target.value }))} value={configuration.codexModel}>{[["gpt-5.6-sol", "5.6 Sol"], ["gpt-5.6-terra", "5.6 Terra"], ["gpt-5.6-luna", "5.6 Luna"], ["gpt-5.5", "5.5"], ["gpt-5.4", "5.4"], ["gpt-5.4-mini", "5.4 Mini"], ["gpt-5.2", "5.2"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block px-3 py-3 text-[10px] text-muted-foreground">推理强度<select className="mt-1.5 block w-full rounded-sm border bg-background px-2 py-2 text-xs text-foreground" onChange={(event) => setConfiguration((value) => ({ ...value, reasoningEffort: event.target.value }))} value={configuration.reasoningEffort}>{[["low", "低"], ["medium", "中"], ["high", "高"], ["xhigh", "极高"], ["max", "最大"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="flex gap-2 border-t p-3"><Button className="flex-1" onClick={() => setConfiguring(false)} type="button" variant="outline">返回</Button><Button className="flex-1" onClick={() => onChoose("codex", configuration)} type="button">创建 Codex 对话</Button></div></section>; return <section className="absolute right-3 top-14 z-30 w-[calc(100%-1.5rem)] overflow-hidden rounded-md border bg-popover shadow-[var(--shadow-overlay)]"><p className="border-b px-3 py-2 text-[10px] font-medium text-muted-foreground">选择 Agent · 创建后不可更改</p><button className="block w-full px-3 py-2.5 text-left text-xs hover:bg-muted" onClick={() => setConfiguring(true)} type="button"><span className="block font-medium">Codex</span><span className="mt-0.5 block text-[10px] text-muted-foreground">可配置模型与推理强度 · 已支持续聊与 Recut MCP</span></button><button className="block w-full border-t px-3 py-2.5 text-left text-xs hover:bg-muted" onClick={() => onChoose("claude")} type="button"><span className="block font-medium">Claude Code</span><span className="mt-0.5 block text-[10px] text-muted-foreground">stream-json adapter · 已支持续聊与 Recut MCP</span></button></section>; }
function codexModelLabel(model?: string) { return ({ "gpt-5.6-sol": "5.6 Sol", "gpt-5.6-terra": "5.6 Terra", "gpt-5.6-luna": "5.6 Luna", "gpt-5.5": "5.5", "gpt-5.4": "5.4", "gpt-5.4-mini": "5.4 Mini", "gpt-5.2": "5.2" } as Record<string, string>)[model || defaultCodexConfiguration.codexModel] ?? "Codex"; }
function reasoningLabel(effort?: string) { return ({ low: "低", medium: "中", high: "高", xhigh: "极高", max: "最大" } as Record<string, string>)[effort || defaultCodexConfiguration.reasoningEffort] ?? "默认推理"; }
