/*
 * [INPUT]: 依赖 WorldStore 的 world_entities 表（script/scene/shot 三层）与 MediaService 的 Asset 生命周期
 * [OUTPUT]: 对外提供 World 生产层读模型：**作品(script) → 场次(scene) → 镜头(shot)** 的树，每个节点带自己的
 *   产物（按需 media 属性）与**自底向上派生**的状态（planned/generating/ready/failed，不落库）
 * [POS]: service 的生产层投影；产物可挂在任一层（镜头产物 / 场成片 / 作品成片），上层状态 = 自身产物 ∪ 子级状态
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
package main

import (
	"database/sql"
	"encoding/json"
)

// Derived production statuses (生产层 RFC §6). Computed, never stored: a stored
// status inevitably goes stale; deriving it from the asset lifecycle is always
// correct. `stale`（上游换料 → 下游过期）lands with the dependency graph (M4).
const (
	ProductionPlanned    = "planned"
	ProductionGenerating = "generating"
	ProductionReady      = "ready"
	ProductionFailed     = "failed"
)

// productionNodeTypes are the entities that form the production tree. `work` is
// the delivery unit (作品) that carries the final cut; `script` is its child (a
// work may have several scripts); `scene`/`shot` are production entities.
// Legacy `story` reads as a work too.
var productionNodeTypes = map[string]bool{"work": true, "script": true, "story": true, "scene": true, "shot": true}

// Production type ids (the two production-entity types).
const (
	ProductionTypeScene = "scene"
	ProductionTypeShot  = "shot"
)

// isProductionProductAttr reports whether an attr is one of a node's products.
// Products are NOT fixed slots: a node is generated by one of several relations
// (reference-driven / first-last-frame / text-driven), so products are ordinary
// on-demand media attrs tagged by label (关键帧/首帧/尾帧/片段/配音/场成片/成片).
// Everything except the card `background` counts. The generation mode itself is
// not a node field — it lives on the produced asset's recipe
// (metadata.proposal: model/modeType/params/references).
func isProductionProductAttr(attr EntityAttr) bool {
	return attr.Type == "media" && attr.Key != "background"
}

// WorldProductionProduct is one product: which attr, its role label, which asset,
// and that asset's current lifecycle status. `assetId` is the reference — the
// asset itself carries the recipe (`metadata.proposal.references` = 用料/role).
type WorldProductionProduct struct {
	Field   string `json:"field"`
	Label   string `json:"label,omitempty"`
	AssetID string `json:"assetId,omitempty"`
	Status  string `json:"status,omitempty"`
}

// WorldProductionNode is one node of the production tree (作品/场次/镜头). A node
// may carry its own products at any level: a shot carries 关键帧/片段/配音, a scene
// carries 场成片, a work carries 成片.
type WorldProductionNode struct {
	ID       string                   `json:"id"`
	TypeID   string                   `json:"typeId"`
	Name     string                   `json:"name"`
	Status   string                   `json:"status"`
	Products []WorldProductionProduct `json:"products"`
	Children []WorldProductionNode    `json:"children"`
}

// WorldProduction is the read model behind the production view.
type WorldProduction struct {
	Roots  []WorldProductionNode `json:"roots"`
	Counts map[string]int        `json:"counts"`
}

// mediaAssetID pulls the assetId out of a media attr value ({assetId,...}).
func mediaAssetID(value any) string {
	payload, ok := value.(map[string]any)
	if !ok {
		return ""
	}
	assetID, _ := payload["assetId"].(string)
	return assetID
}

// nodeProducts extracts a node's product attrs, skipping empty slots (the status
// already says "not produced yet"; the caller does not need placeholder noise).
func nodeProducts(attrs []EntityAttr, lookup func(string) string) []WorldProductionProduct {
	products := []WorldProductionProduct{}
	for _, attr := range attrs {
		if !isProductionProductAttr(attr) {
			continue
		}
		assetID := mediaAssetID(attr.Value)
		if assetID == "" {
			continue
		}
		products = append(products, WorldProductionProduct{Field: attr.Key, Label: attr.Label, AssetID: assetID, Status: lookup(assetID)})
	}
	return products
}

// rollupProductionStatus derives a node's status from its own products and its
// children, bottom-up and monotone: failed > generating > ready > planned.
//   - any own product (or child) failed/deleted      → failed
//   - any own product (or child) still coming        → generating
//   - nothing attached anywhere                      → planned
//   - all own products completed && all children ready → ready
//   - otherwise (some progress exists)               → generating
//
// It reports the objective asset lifecycle, not creative completeness: "how many
// products this node should have" is the plan's call (M3), not the status's.
func rollupProductionStatus(own []WorldProductionProduct, children []WorldProductionNode) string {
	failed, generating, completed := 0, 0, 0
	for _, product := range own {
		switch product.Status {
		case "completed":
			completed++
		case "failed", "deleted":
			failed++
		default:
			generating++
		}
	}
	childReady, childFailed, childGenerating := 0, 0, 0
	for _, child := range children {
		switch child.Status {
		case ProductionReady:
			childReady++
		case ProductionFailed:
			childFailed++
		case ProductionGenerating:
			childGenerating++
		}
	}
	if failed+childFailed > 0 {
		return ProductionFailed
	}
	if generating+childGenerating > 0 {
		return ProductionGenerating
	}
	if len(own)+len(children) == 0 {
		return ProductionPlanned
	}
	if completed == len(own) && childReady == len(children) {
		return ProductionReady
	}
	if completed > 0 || childReady > 0 {
		return ProductionGenerating
	}
	return ProductionPlanned
}

// productionRecord is one row of the raw production query before the tree is built.
type productionRecord struct {
	id, typeID, name, parentID string
	attrs                      []EntityAttr
}

// ProductionStatus reads a world's production tree (作品 → 场次 → 镜头) and derives
// each node's status from its own product assets plus its children. Pure read: it
// persists nothing (生产层 RFC §6.1「状态派生而非存储」).
func (w *WorldStore) ProductionStatus(worldID string) (WorldProduction, error) {
	db, err := w.database()
	if err != nil {
		return WorldProduction{}, err
	}
	if _, err := w.summary(db, worldID); err != nil {
		return WorldProduction{}, err
	}
	rows, err := db.Query("select id, coalesce(nullif(type_id, ''), kind), title, attrs_json, parent_id from world_entities where world_id = ? and archived_at is null order by created_at", worldID)
	if err != nil {
		return WorldProduction{}, err
	}
	defer rows.Close()

	records := map[string]productionRecord{}
	order := []string{}
	for rows.Next() {
		var rec productionRecord
		var attrsJSON string
		var parentID sql.NullString
		if err := rows.Scan(&rec.id, &rec.typeID, &rec.name, &attrsJSON, &parentID); err != nil {
			return WorldProduction{}, err
		}
		if !productionNodeTypes[rec.typeID] {
			continue
		}
		rec.parentID = nullStringValue(parentID)
		if attrsJSON != "" {
			_ = json.Unmarshal([]byte(attrsJSON), &rec.attrs)
		}
		records[rec.id] = rec
		order = append(order, rec.id)
	}
	if err := rows.Err(); err != nil {
		return WorldProduction{}, err
	}

	// The production tree is expressed by structural links — has_script /
	// has_scene / has_shot — NOT by parentId: parentId is only a generic
	// location (folder). Links are the single source of truth (生产层 RFC D8);
	// cycles are allowed and broken during traversal.
	relationRows, err := db.Query("select from_entity_id, to_entity_id from world_relations where world_id = ? and relation_type in ('has_script','has_scene','has_shot')", worldID)
	if err != nil {
		return WorldProduction{}, err
	}
	childrenOf := map[string][]string{}
	hasParent := map[string]bool{}
	for relationRows.Next() {
		var fromID, toID string
		if err := relationRows.Scan(&fromID, &toID); err != nil {
			relationRows.Close()
			return WorldProduction{}, err
		}
		if _, ok := records[fromID]; !ok {
			continue
		}
		if _, ok := records[toID]; !ok {
			continue
		}
		childrenOf[fromID] = append(childrenOf[fromID], toID)
		hasParent[toID] = true
	}
	relationRows.Close()
	if err := relationRows.Err(); err != nil {
		return WorldProduction{}, err
	}
	roots := []string{}
	for _, id := range order {
		if !hasParent[id] {
			roots = append(roots, id)
		}
	}

	// One asset lookup per distinct assetId.
	assetStatuses := map[string]string{}
	lookup := func(assetID string) string {
		if assetID == "" || w.media == nil {
			return ""
		}
		if status, ok := assetStatuses[assetID]; ok {
			return status
		}
		status := ""
		if asset, err := w.media.GetAsset(assetID); err == nil {
			status = asset.Status
		}
		assetStatuses[assetID] = status
		return status
	}

	// Post-order build: children first, so a parent's status can roll them up.
	// `visited` makes traversal cycle-safe (a link graph, unlike a tree, may
	// contain cycles); any node reachable only through a cycle is surfaced as an
	// extra root below so no production node is silently dropped.
	counts := map[string]int{}
	visited := map[string]bool{}
	var build func(id string) WorldProductionNode
	build = func(id string) WorldProductionNode {
		rec := records[id]
		products := nodeProducts(rec.attrs, lookup)
		children := []WorldProductionNode{}
		for _, childID := range childrenOf[id] {
			if visited[childID] {
				continue
			}
			visited[childID] = true
			children = append(children, build(childID))
		}
		status := rollupProductionStatus(products, children)
		counts[status]++
		return WorldProductionNode{ID: rec.id, TypeID: rec.typeID, Name: rec.name, Status: status, Products: products, Children: children}
	}

	result := WorldProduction{Roots: []WorldProductionNode{}, Counts: counts}
	for _, id := range roots {
		if visited[id] {
			continue
		}
		visited[id] = true
		result.Roots = append(result.Roots, build(id))
	}
	for _, id := range order {
		if visited[id] {
			continue
		}
		visited[id] = true
		result.Roots = append(result.Roots, build(id))
	}
	return result, nil
}
