/*
 * [INPUT]: 依赖 Media Platform 资产 API、系统项目 Agent Session 与可拖拽侧栏组件
 * [OUTPUT]: 对外提供左侧素材管理、右侧 Agent 协作的工作区级素材库系统应用
 * [POS]: web/app/media 的系统应用入口；Provider 配置属于全局 SettingsPanel，不属于素材库
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
"use client";

import { ArrowLeft, ImageIcon, Music2, Video, X } from "lucide-react";
import Link from "next/link";
import { CSSProperties, useEffect, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { ProjectAgentPanel } from "@/components/project-agent-panel";
import { SettingsPanel } from "@/components/settings-panel";
import { useResizableSidePanel } from "@/components/use-resizable-side-panel";

const apiBase = process.env.NEXT_PUBLIC_RECUT_API_URL ?? "http://127.0.0.1:17373";
type Asset = { id: string; kind: "image" | "video" | "audio"; name: string; origin: string; createdAt: string; metadata: { prompt?: string } };
type Filter = "all" | Asset["kind"];
const filters: { id: Filter; label: string; icon: typeof ImageIcon }[] = [{ id: "all", label: "全部", icon: ImageIcon }, { id: "image", label: "图片", icon: ImageIcon }, { id: "video", label: "视频", icon: Video }, { id: "audio", label: "音频", icon: Music2 }];

export default function MediaLibrary() {
  const [assets, setAssets] = useState<Asset[]>([]); const [filter, setFilter] = useState<Filter>("all"); const [online, setOnline] = useState(false); const [projectID, setProjectID] = useState<string | null>(null); const [preview, setPreview] = useState<Asset | null>(null);
  const { handlePointerDown, layoutRef, panelWidth } = useResizableSidePanel({ storageKey: "recut.media-agent-panel-width" });
  async function load() { try { const [health, project, assetResponse] = await Promise.all([fetch(`${apiBase}/health`), fetch(`${apiBase}/v1/media/system-project`), fetch(`${apiBase}/v1/media/assets`)]); if (!health.ok || !project.ok || !assetResponse.ok) throw new Error(); setProjectID((await project.json()).id); setAssets(await assetResponse.json()); setOnline(true); } catch { setOnline(false); } }
  useEffect(() => { void load(); const interval = window.setInterval(() => void load(), 3000); return () => window.clearInterval(interval); }, []);
  const visibleAssets = filter === "all" ? assets : assets.filter((asset) => asset.kind === filter);
  return <main className="flex h-screen min-w-[1024px] flex-col overflow-hidden bg-background"><header className="flex h-14 shrink-0 items-center justify-between border-b bg-card px-5"><div className="flex items-center gap-3"><Link aria-label="返回项目工作区" className="grid size-8 place-items-center rounded-xs hover:bg-muted" href="/"><ArrowLeft className="size-4" /></Link><ImageIcon className="size-4" /><strong className="text-sm">素材库</strong><Badge>WORKSPACE</Badge></div><div className="flex items-center gap-3"><span className="font-mono text-[10px] text-muted-foreground">{online ? "DAEMON CONNECTED" : "DAEMON OFFLINE"}</span><SettingsPanel /></div></header><div className="relative grid min-h-0 flex-1 overflow-hidden [grid-template-columns:minmax(0,1fr)_var(--side-panel-width)]" ref={layoutRef} style={{ "--side-panel-width": `${panelWidth}px` } as CSSProperties}><section className="min-h-0 overflow-y-auto p-8"><div className="mx-auto max-w-5xl"><div className="mb-6 flex items-end justify-between border-b pb-4"><div><h1 className="text-2xl font-semibold">媒体资产</h1><p className="mt-1 text-xs text-muted-foreground">让右侧 Agent 根据全局模型配置创建内容；生成完成后这里会自动更新。</p></div><Badge>{visibleAssets.length} ASSETS</Badge></div><nav className="mb-5 flex gap-2">{filters.map((item) => { const Icon = item.icon; return <button className={`flex h-8 items-center gap-1.5 rounded-xs border px-2.5 text-xs ${filter === item.id ? "bg-secondary font-medium" : "bg-card text-muted-foreground hover:bg-muted"}`} key={item.id} onClick={() => setFilter(item.id)} type="button"><Icon className="size-3.5" />{item.label}</button>; })}</nav><AssetGrid assets={visibleAssets} onPreview={setPreview} /></div></section><button aria-label="拖动调整 Agent 面板宽度" className="group absolute inset-y-0 z-10 w-2 cursor-col-resize border-0 bg-transparent p-0 [left:calc(100%_-_var(--side-panel-width)_-_0.25rem)]" onPointerDown={handlePointerDown} type="button"><span className="absolute inset-y-0 left-1/2 w-px -translate-x-1/2 bg-border group-hover:w-0.5 group-hover:bg-foreground" /></button><ProjectAgentPanel apiBase={apiBase} online={online} projectID={projectID} /></div>{preview && <AssetPreview asset={preview} onClose={() => setPreview(null)} />}</main>;
}

function AssetGrid({ assets, onPreview }: { assets: Asset[]; onPreview: (asset: Asset) => void }) {
  if (!assets.length) return <div className="grid min-h-72 place-items-center rounded-xs border border-dashed bg-card text-center"><div><ImageIcon className="mx-auto size-5 text-muted-foreground" /><p className="mt-3 text-sm font-medium">还没有素材</p><p className="mt-1 text-xs text-muted-foreground">在右侧告诉 Agent 想创建什么，它会按全局配置调用对应 Provider。</p></div></div>;
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{assets.map((asset) => <button className="overflow-hidden rounded-xs border bg-card text-left transition-colors hover:border-foreground/40 hover:bg-muted/20" key={asset.id} onClick={() => onPreview(asset)} type="button">{asset.kind === "image" ? <div className="aspect-[4/3] bg-muted"><img alt={asset.name} className="h-full w-full object-cover" src={`${apiBase}/v1/media/assets/${asset.id}/content`} /></div> : <div className="grid aspect-[4/3] place-items-center bg-muted"><span className="text-xs text-muted-foreground">{asset.kind.toUpperCase()}</span></div>}<div className="p-3"><p className="truncate text-xs font-medium">{asset.name}</p><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-muted-foreground">{asset.metadata.prompt ?? "导入素材"}</p><div className="mt-3 flex justify-between font-mono text-[10px] text-muted-foreground"><span>{asset.origin.toUpperCase()}</span><span>{new Date(asset.createdAt).toLocaleDateString()}</span></div></div></button>)}</div>;
}

function AssetPreview({ asset, onClose }: { asset: Asset; onClose: () => void }) { return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-8 backdrop-blur-[1px]" onMouseDown={onClose} role="dialog"><section className="w-full max-w-4xl overflow-hidden rounded-sm border bg-card shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><header className="flex items-center justify-between border-b px-5 py-3"><div><p className="text-sm font-medium">{asset.name}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{asset.kind.toUpperCase()} · {asset.origin.toUpperCase()}</p></div><button aria-label="关闭预览" className="grid size-8 place-items-center rounded-xs text-muted-foreground hover:bg-muted" onClick={onClose} type="button"><X className="size-4" /></button></header><div className="grid max-h-[78vh] overflow-y-auto md:grid-cols-[minmax(0,1fr)_260px]"><div className="grid min-h-80 place-items-center bg-muted/30 p-5">{asset.kind === "image" ? <img alt={asset.name} className="max-h-[65vh] max-w-full object-contain" src={`${apiBase}/v1/media/assets/${asset.id}/content`} /> : <p className="text-xs text-muted-foreground">{asset.kind.toUpperCase()} 预览将在此显示。</p>}</div><aside className="border-l p-5"><p className="text-xs font-medium">生成信息</p><dl className="mt-4 space-y-4 text-xs"><div><dt className="text-muted-foreground">提示词</dt><dd className="mt-1 leading-5">{asset.metadata.prompt ?? "无"}</dd></div><div><dt className="text-muted-foreground">创建时间</dt><dd className="mt-1">{new Date(asset.createdAt).toLocaleString()}</dd></div></dl></aside></div></section></div>; }
