/*
 * [INPUT]: 依赖 Locale 与 LandingStep；依据 Cover Studio 的渠道规格、两类参考、双生成入口、归档预览和历史记录契约
 * [OUTPUT]: 对外提供 CoverStudioLanding
 * [POS]: Cover Studio 专属营销 Landing；用画板、双路径和可追溯历史表达真实封面创作台，不与其他 App 共享主体布局
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
import type { Locale } from "@/lib/i18n";
import { LandingStep } from "./landing-primitives";

export function CoverStudioLanding({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="border-t border-white/10 pt-14"><section className="grid gap-8 lg:grid-cols-[1.12fr_.88fr] lg:items-center"><CoverBoard locale={locale} /><div><p className="font-mono text-[10px] font-semibold tracking-[.18em] text-primary">{zh ? "视频创作最后一站" : "THE LAST STOP OF VIDEO CREATION"}</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">{zh ? "视频剪完了，封面才决定它怎么被看见。" : "The edit is finished. The cover decides how it gets seen."}</h2><p className="mt-5 text-sm leading-6 text-muted-foreground">{zh ? "一张好的封面是视频的门面。Cover Studio 不让你凭空猜 Prompt，而是用真实场景和参考封面，把设计方向带进每一次生成。" : "A strong cover is the front door of a video. Cover Studio starts from real scenes and reference covers instead of making you guess a prompt from scratch."}</p></div></section><ReferenceLogic locale={locale} /><GenerationRoutes locale={locale} /><ArchivedHistory locale={locale} /></section>;
}

function CoverBoard({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <article className="relative min-h-80 overflow-hidden rounded-2xl border border-white/10 bg-[#121817] p-5 shadow-[inset_0_1px_rgba(255,255,255,.05)]"><header className="relative z-10 flex items-center justify-between font-mono text-[9px] text-white/40"><span>NEW COVER / 1280 × 720</span><span className="rounded bg-primary/15 px-2 py-1 text-primary">YOUTUBE</span></header><div className="absolute bottom-6 left-6 right-[18%] top-14 overflow-hidden rounded-xl bg-[radial-gradient(circle_at_75%_25%,#e5c183_0_7%,transparent_22%),linear-gradient(135deg,#455e5e,#19292f_48%,#b56a4e)]"><span className="absolute bottom-0 left-[12%] h-[65%] w-[34%] rounded-t-[50%] bg-black/30" /><span className="absolute bottom-[12%] left-[47%] h-9 w-9 rounded-full border-2 border-white/30" /><span className="absolute bottom-[13%] left-[60%] h-20 w-2 rotate-[22deg] rounded bg-white/35" /><span className="absolute bottom-5 left-5 right-5 h-2 rounded bg-black/20" /></div><div className="absolute bottom-7 right-5 grid w-[31%] gap-2"><div className="aspect-[4/3] rounded-lg border border-white/15 bg-[linear-gradient(135deg,#c69666,#425768)]" /><div className="aspect-[4/3] rounded-lg border border-white/15 bg-[linear-gradient(135deg,#5b476f,#d58059)]" /><p className="font-mono text-[8px] text-white/35">REFERENCE BOARD</p></div><p className="absolute bottom-5 left-5 rounded-md bg-black/35 px-2 py-1 font-mono text-[8px] text-white/65">PREVIEW / DRAFT</p></article>;
}

function ReferenceLogic({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 grid gap-5 lg:grid-cols-[.78fr_1.22fr]"><div className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="01" label={zh ? "视频创作最后一站" : "THE FINAL VIDEO STEP"} /><h3 className="mt-5 text-xl font-semibold">{zh ? "不是自己猜 Prompt，而是从真实封面开始设计。" : "Do not guess a prompt. Design from a real cover."}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{zh ? "先选渠道和画幅，再从真实场景参考里找到构图、主体和留白。封面从一开始就为点击和识别服务，而不是剪完后临时补一张图。" : "Choose the channel and canvas, then use real scene references to find composition, subject and negative space. The cover serves recognition and the click from the start."}</p><div className="mt-5 grid grid-cols-2 gap-2 font-mono text-[9px]"><span className="rounded-lg border border-primary/35 bg-primary/[.09] px-3 py-2 text-primary">YouTube · 16:9</span><span className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-white/45">Xiaohongshu · 3:4</span></div></div><div className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="02" label={zh ? "两类真实参考" : "TWO REAL REFERENCE TYPES"} /><div className="mt-5 grid gap-4 sm:grid-cols-2"><ReferenceCard gradient="bg-[linear-gradient(135deg,#d4b17f,#3d5d5b)]" label={zh ? "内容参考" : "SUBJECT REFERENCE"} text={zh ? "人物、产品与物体：锁定这期视频要讲什么。" : "People, products and objects: lock what this episode is about."} /><ReferenceCard gradient="bg-[linear-gradient(135deg,#573e70,#cf7854)]" label={zh ? "参考封面" : "REFERENCE COVER"} text={zh ? "构图、留白与语气：借真实案例说明应该怎么讲。" : "Composition, negative space and tone: show how the cover should speak."} /></div></div></section>;
}

function GenerationRoutes({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 rounded-2xl border border-primary/25 bg-primary/[.055] p-5 sm:p-7"><div className="max-w-2xl"><p className="font-mono text-[10px] font-semibold tracking-[.18em] text-primary">TWO VISIBLE ROUTES</p><h3 className="mt-4 text-2xl font-semibold tracking-[-.03em]">{zh ? "从真实参考出发，快速找到能撑起视频门面的封面。" : "Start from real references and find a cover worthy of the video."}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{zh ? "一条路径直接使用已连接的图片模型；另一条把完整任务书交给 Codex。两条路径都保留参考来源，不需要你从一张白纸猜 Prompt。" : "One route uses the connected image model directly; the other stages a full brief for Codex. Both preserve the reference source, so you never start by guessing a prompt."}</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><RouteCard accent icon="✦" label={zh ? "直接生成" : "DIRECT MODEL"} detail={zh ? "立即从已配置模型生成候选图。" : "Generate candidates with the configured model."} /><RouteCard icon="›_" label={zh ? "交给 Codex" : "STAGE FOR CODEX"} detail={zh ? "可编辑任务书，确认后才真正发送。" : "An editable task brief, sent only on confirmation."} /></div></section>;
}

function ArchivedHistory({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 grid gap-5 lg:grid-cols-[1.12fr_.88fr]"><div className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="03" label={zh ? "归档真实交付" : "ARCHIVE REAL DELIVERY"} /><div className="mt-5 grid grid-cols-3 gap-3">{["#c18765,#3b5c63", "#4a4b73,#ce8d65", "#5c6a45,#c9876d"].map((colors, index) => <div className="relative aspect-[4/3] overflow-hidden rounded-xl border border-white/10" key={colors} style={{ background: `linear-gradient(135deg,${colors})` }}><span className="absolute bottom-2 left-2 rounded bg-black/30 px-1.5 py-1 font-mono text-[8px] text-white/65">{index === 1 ? "CURRENT" : `V0${index + 1}`}</span></div>)}</div></div><div className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><h3 className="text-xl font-semibold">{zh ? "历史记录的是决策，不复制文件。" : "History records decisions, not duplicate files."}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{zh ? "只有归档后的真实 assetId 会出现在预览和历史中，并保留 prompt、渠道、尺寸与两类参考。默认不要求模型画出可读文字、Logo 或水印，把可控排版留给后续步骤。" : "Only archived assetIds appear in preview and history, together with prompt, channel, size and both references. Readable text, logos and watermarks stay out by default, leaving typography controllable later."}</p></div></section>;
}

function ReferenceCard({ gradient, label, text }: { gradient: string; label: string; text: string }) { return <div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className={`aspect-video rounded-lg ${gradient}`} /><p className="mt-3 font-mono text-[9px] text-primary">{label}</p><p className="mt-2 text-[11px] leading-5 text-white/50">{text}</p></div>; }
function RouteCard({ accent, detail, icon, label }: { accent?: boolean; detail: string; icon: string; label: string }) { return <div className={`rounded-xl border p-5 ${accent ? "border-primary/40 bg-primary/[.1]" : "border-white/10 bg-black/20"}`}><span className="font-mono text-lg text-primary">{icon}</span><h4 className="mt-5 text-sm font-semibold">{label}</h4><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></div>; }
