/*
 * [INPUT]: 依赖 Locale 与 LandingMetric/LandingStep；依据 Depth Anything V2 的本机模型、图片/逐帧视频推理、可取消任务与显式保存契约
 * [OUTPUT]: 对外提供 DepthAnythingLanding
 * [POS]: Depth Anything 专属营销 Landing；用输入输出对照、模型控制台与视频任务管线表达本地深度图工作流
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
import type { Locale } from "@/lib/i18n";
import { LandingMetric, LandingStep } from "./landing-primitives";

export function DepthAnythingLanding({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="border-t border-white/10 pt-14"><section className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="font-mono text-[10px] font-semibold tracking-[.18em] text-primary">{zh ? "生成参考的深度底图" : "DEPTH REFERENCE PASS"}</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">{zh ? "给图片和视频生成更干净、更可信的参考。" : "Give image and video generation a cleaner, stronger reference."}</h2><p className="mt-5 max-w-md text-sm leading-6 text-muted-foreground">{zh ? "深度图不是最终成品，而是给生成模型看的结构提示：去掉前后景混在一起的噪音，让图片或视频生成更容易理解主体、空间和层次。" : "A depth map is not the final image. It is a structural signal for generation: less foreground/background noise, clearer subjects, space and layers for image and video models to follow."}</p></div><DepthComparison locale={locale} /></section><ModelConsole locale={locale} /><VideoPipeline locale={locale} /><PrivateSave locale={locale} /></section>;
}

function DepthComparison({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <article className="overflow-hidden rounded-2xl border border-white/10 bg-card p-4 sm:p-5"><header className="flex items-center justify-between font-mono text-[9px] text-white/40"><span>DEPTH ANYTHING V2</span><span className="text-primary">IMAGE MODE</span></header><div className="relative mt-4 grid grid-cols-2 gap-2"><div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-[radial-gradient(circle_at_68%_27%,#e0ba7c_0_9%,transparent_10%),linear-gradient(135deg,#31595a,#1d3038_60%,#c47757)]"><span className="absolute bottom-0 left-[14%] h-[63%] w-[34%] rounded-t-[50%] bg-[#151b24]/75" /><span className="absolute bottom-[12%] right-[18%] h-[34%] w-[18%] rounded-full bg-[#e0b376]/70" /><p className="absolute left-3 top-3 rounded bg-black/25 px-2 py-1 font-mono text-[8px] text-white/65">INPUT</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-[linear-gradient(135deg,#f4f3dc,#7f99c2_46%,#19203a)]"><span className="absolute inset-y-0 left-[29%] w-7 bg-white/30 blur-md" /><span className="absolute inset-y-0 left-[55%] w-5 bg-[#21366c]/35 blur-sm" /><span className="absolute bottom-[12%] right-[18%] h-[34%] w-[18%] rounded-full bg-[#f4f3dc]/60 blur-[2px]" /><p className="absolute left-3 top-3 rounded bg-black/20 px-2 py-1 font-mono text-[8px] text-white/65">DEPTH / COLOR</p></div><span className="pointer-events-none absolute bottom-0 left-1/2 top-0 w-px bg-primary shadow-[0_0_12px_#8ee9a6]" /></div><p className="mt-4 text-[11px] leading-5 text-white/45">{zh ? "同一个输入可选择伪彩或灰度输出，先在私有预览里看边缘和层次。" : "The same input can produce colorized or grayscale depth, previewed privately before you save it."}</p></article>;
}

function ModelConsole({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 rounded-2xl border border-white/10 bg-card p-5 sm:p-7"><div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><div><LandingStep step="01" label={zh ? "为生成准备参考" : "PREPARE THE GENERATION REFERENCE"} /><h3 className="mt-4 text-2xl font-semibold tracking-[-.03em]">{zh ? "先把主体和空间理清，再交给生成模型。" : "Clarify the subject and space before generation."}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{zh ? "Small 适合快速去噪确认，Base 是平衡默认，Large 用于更细的边缘与更稳定的视频逐帧结果。" : "Small is for fast denoising checks, Base is the balanced default, and Large brings finer edges and steadier frame-by-frame video results."}</p></div><div className="grid gap-3 sm:grid-cols-3"><ModelCard label="SMALL" note={zh ? "快速预览" : "FAST PREVIEW"} value="↑ speed" /><ModelCard active label="BASE" note={zh ? "默认平衡" : "BALANCED DEFAULT"} value="recommended" /><ModelCard label="LARGE" note={zh ? "细节与稳定性" : "DETAIL + STABILITY"} value="↑ fidelity" /></div></div></section>;
}

function VideoPipeline({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><article className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="02" label={zh ? "视频逐帧，不是假装成图片" : "VIDEO, FRAME BY FRAME"} /><div className="mt-5 flex items-center gap-2"><Frame label="01" /><span className="h-px flex-1 bg-primary/35" /><Frame label="02" /><span className="h-px flex-1 bg-primary/35" /><Frame label="03" /><span className="text-xl text-primary">→</span><div className="grid h-14 w-20 place-items-center rounded-lg border border-primary/35 bg-primary/[.08] font-mono text-[9px] text-primary">H.264<br />MP4</div></div><p className="mt-5 text-xs leading-5 text-muted-foreground">{zh ? "视频会逐帧推理，再通过 FFmpeg 转为浏览器可预览的 H.264/yuv420p MP4。它不是静态深度图套在视频上的假效果。" : "Videos are inferred frame by frame, then transcoded with FFmpeg into previewable H.264/yuv420p MP4—not a static depth-image effect pasted over footage."}</p></article><article className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="03" label={zh ? "每一步都可以停止" : "EVERY STEP CAN STOP"} /><div className="mt-5 rounded-xl border border-white/10 bg-black/25 p-4 font-mono text-[10px] leading-6 text-white/50"><p><span className="text-primary">✓</span> model ready / Base</p><p><span className="text-primary">✓</span> frames 128 / 240</p><p><span className="text-primary">›</span> transcoding preview.mp4</p><p className="mt-2 text-white/30">cancel() available</p></div><p className="mt-4 text-xs leading-5 text-muted-foreground">{zh ? "安装、模型下载和推理都是可取消任务；进度、错误和任务日志不会藏起来。" : "Install, model download and inference are cancellable jobs; progress, errors and task logs stay visible."}</p></article></section>;
}

function PrivateSave({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 grid gap-5 rounded-2xl border border-primary/25 bg-primary/[.055] p-5 sm:grid-cols-[.8fr_1.2fr] sm:p-7"><div><p className="font-mono text-[10px] font-semibold tracking-[.18em] text-primary">PRIVATE PREVIEW</p><h3 className="mt-4 text-2xl font-semibold tracking-[-.03em]">{zh ? "把干净的参考底图交给下一步生成。" : "Hand a clean reference pass to the next generation step."}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{zh ? "先预览和确认去噪后的结构，再保存为真实 Asset，接回图片生成、视频生成或后期合成。depth.generate 不自动入库，只有你确认后才调用 depth.save。" : "Preview and approve the denoised structure, then save a real Asset for image generation, video generation or compositing. depth.generate stays private until you confirm depth.save."}</p></div><div className="grid gap-3 sm:grid-cols-2"><LandingMetric title={zh ? "生成结果" : "GENERATE RESULT"} value={zh ? "干净的生成参考" : "Clean generation reference"} /><LandingMetric title={zh ? "明确保存" : "EXPLICIT SAVE"} value={zh ? "真实 PNG / MP4 Asset" : "Real PNG / MP4 Asset"} /></div></section>;
}

function ModelCard({ active, label, note, value }: { active?: boolean; label: string; note: string; value: string }) { return <div className={`rounded-xl border p-4 ${active ? "border-primary/45 bg-primary/[.08]" : "border-white/10 bg-black/20"}`}><p className={`font-mono text-[10px] ${active ? "text-primary" : "text-white/50"}`}>{label}</p><p className="mt-5 text-sm font-semibold">{note}</p><p className="mt-2 text-[10px] text-white/45">{value}</p></div>; }
function Frame({ label }: { label: string }) { return <div className="relative grid size-14 place-items-center overflow-hidden rounded-lg border border-white/10 bg-[linear-gradient(135deg,#4b6e70,#bc795d)] font-mono text-[8px] text-white/65"><span className="absolute inset-y-0 left-1/2 w-3 bg-white/10" />{label}</div>; }
