/*
 * [INPUT]: 依赖 Locale 与 LandingStep；依据 Remotion Studio 的 Brief、项目私有 workspace、Vite HMR、素材/字体物化和本地确定性导出契约
 * [OUTPUT]: 对外提供 RemotionStudioLanding
 * [POS]: Remotion Studio 专属营销 Landing；以真实代码工程、热更新预览和可复现渲染台表达产品价值
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
import type { Locale } from "@/lib/i18n";
import { LandingStep } from "./landing-primitives";

const code = ["export const ProjectVideo = () => {", "  const frame = useCurrentFrame();", "  return <Sequence from={0}>", "    <Caption theme=\"kinetic\" />", "  </Sequence>;", "};"];

export function RemotionStudioLanding({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="border-t border-white/10 pt-14"><section className="grid gap-8 lg:grid-cols-[1.18fr_.82fr] lg:items-center"><WorkspaceFrame locale={locale} /><div><p className="font-mono text-[10px] font-semibold tracking-[.18em] text-primary">{zh ? "不要从零开始" : "DO NOT START FROM ZERO"}</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">{zh ? "用现成模板、组件和素材库，把视频做成代码。" : "Turn video into code with ready-made templates, components and media."}</h2><p className="mt-5 text-sm leading-6 text-muted-foreground">{zh ? "Remotion Studio 不是空白工程：内置丰富模板、动态组件、特效、字幕主题、字体库和音乐库。你从一个可运行的 Brief 开始，再按需要改代码。" : "Remotion Studio is not a blank repo: it includes templates, motion components, effects, caption themes, a font library and a music library. Start from a working Brief, then change the code where needed."}</p></div></section><BriefToWorkspace locale={locale} /><LivePreview locale={locale} /><DeterministicRender locale={locale} /></section>;
}

function WorkspaceFrame({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <article className="overflow-hidden rounded-2xl border border-white/10 bg-[#111716]"><header className="flex items-center gap-2 border-b border-white/10 px-4 py-3"><span className="size-2 rounded-full bg-[#e16c59]" /><span className="size-2 rounded-full bg-[#d6a759]" /><span className="size-2 rounded-full bg-[#69a875]" /><span className="ml-2 font-mono text-[9px] text-white/40">workspace / ProjectVideo.tsx</span></header><div className="grid min-h-64 grid-cols-[.95fr_1.05fr]"><div className="border-r border-white/10 bg-black/25 p-4 font-mono text-[9px] leading-6 text-white/55">{code.map((line, index) => <p className={index === 3 ? "text-primary" : ""} key={line}><span className="mr-3 text-white/20">{index + 1}</span>{line}</p>)}</div><div className="relative grid place-items-center p-5"><div className="relative aspect-[9/16] h-48 overflow-hidden rounded-lg bg-[radial-gradient(circle_at_55%_28%,#e3bd83_0_7%,transparent_18%),linear-gradient(165deg,#3b6571,#231f34_65%,#c9775b)] shadow-2xl"><p className="absolute bottom-7 left-4 right-4 text-center text-xs font-semibold leading-5 text-white">{zh ? "把故事写进每一帧。" : "Make every frame tell the story."}</p><span className="absolute bottom-4 left-4 right-4 h-1 rounded bg-white/40" /></div><span className="absolute bottom-4 right-4 font-mono text-[8px] text-primary">@remotion/player</span></div></div></article>;
}

function BriefToWorkspace({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 grid gap-5 lg:grid-cols-[.82fr_1.18fr]"><article className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="01" label={zh ? "从现成能力开始" : "START WITH READY-MADE BUILDING BLOCKS"} /><h3 className="mt-5 text-xl font-semibold">{zh ? "模板、组件、特效、字体和音乐都已经在里面。" : "Templates, components, effects, fonts and music are already inside."}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{zh ? "你不用先搭 React、Remotion、字幕和资源管线；先选一个成片模板，再填选题、文案、SRT 和素材。" : "You do not have to scaffold React, Remotion, captions or asset plumbing first. Pick a composition template, then bring your topic, copy, SRT and media."}</p><div className="mt-5 flex flex-wrap gap-2"><Chip label="TEMPLATES" /><Chip label="COMPONENTS" /><Chip label="EFFECTS" /><Chip label="FONTS" /><Chip label="MUSIC" /></div></article><article className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="02" label={zh ? "Brief → 独立 workspace" : "BRIEF → PRIVATE WORKSPACE"} /><div className="mt-5 grid gap-3 sm:grid-cols-[.7fr_1.3fr]"><div className="rounded-xl border border-white/10 bg-black/25 p-3 font-mono text-[9px] text-white/45"><p className="text-primary">workspace/</p><p className="mt-2">src/</p><p className="pl-3">compositions/</p><p className="pl-6 text-white/70">ProjectVideo.tsx</p><p className="mt-2">preview/props.json</p></div><p className="text-xs leading-5 text-muted-foreground">{zh ? "首次从 remotion-skeleton 完整复制；AI 改的是这个项目自己的 composition 代码，项目间不会互相污染。" : "The workspace begins as a full remotion-skeleton copy. AI changes this project’s own composition code, never another project’s."}</p></div></article></section>;
}

function LivePreview({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 rounded-2xl border border-primary/25 bg-primary/[.055] p-5 sm:p-7"><div className="grid gap-6 lg:grid-cols-[.76fr_1.24fr]"><div><p className="font-mono text-[10px] font-semibold tracking-[.18em] text-primary">VITE HMR</p><h3 className="mt-4 text-2xl font-semibold tracking-[-.03em]">{zh ? "改一行代码，播放器立刻响应。" : "Edit code. The player responds immediately."}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{zh ? "每个项目都有自己的 Vite dev server；iframe 内的 @remotion/player 用 HMR 预览真实 composition。你可以继续替换字幕主题、画布、动态组件、素材、音乐和字体。" : "Every project gets its own Vite dev server. The iframe @remotion/player previews the real composition through HMR. Keep tuning caption themes, canvas, motion components, media, music and fonts."}</p></div><div className="rounded-xl border border-white/10 bg-black/25 p-4"><div className="flex items-center justify-between font-mono text-[9px] text-white/40"><span>LIVE PREVIEW</span><span className="text-primary">HMR CONNECTED</span></div><div className="mt-4 aspect-[16/7] rounded-lg bg-[linear-gradient(135deg,#334f55,#1b2330_60%,#a96450)] p-4"><span className="inline-block rounded bg-black/25 px-2 py-1 font-mono text-[8px] text-white/70">scene / 04</span><p className="mt-10 max-w-[60%] text-lg font-semibold leading-tight">{zh ? "本地代码，实时画面。" : "Local code, live picture."}</p></div><div className="mt-3 flex items-center gap-3"><span className="size-7 rounded-full bg-primary text-center leading-7 text-primary-foreground">▶</span><div className="h-1 flex-1 rounded bg-white/10"><span className="block h-full w-[38%] rounded bg-primary" /></div><span className="font-mono text-[9px] text-white/40">00:18 / 00:48</span></div></div></div></section>;
}

function DeterministicRender({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  return <section className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><article className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><LandingStep step="03" label={zh ? "预览与导出同一套帧逻辑" : "ONE FRAME LOGIC FOR PREVIEW + EXPORT"} /><div className="mt-5 flex items-center gap-2"><Pipeline label="Composition" /><span className="text-primary">→</span><Pipeline label="@remotion/player" /><span className="text-primary">→</span><Pipeline active label="Local MP4" /></div><p className="mt-5 text-xs leading-5 text-muted-foreground">{zh ? "composition 和字幕全部从 frame 派生，预览与导出逐帧一致。导出由本机 headless Chrome 渲染，成功后归档为 Recut Media，并成为项目封面。" : "Composition and captions are frame-derived, so preview and render match frame-for-frame. Local headless Chrome renders the MP4, which is archived into Recut Media and becomes the project cover."}</p></article><article className="rounded-2xl border border-white/10 bg-card p-5 sm:p-6"><h3 className="text-xl font-semibold">{zh ? "音乐与字体也要物化到本地。" : "Music and fonts become local too."}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{zh ? "你可以先从 CDN 试听和预览；真正导出前，BGM 与字体都会物化为本地资源，避免渲染时依赖不可控的网络。" : "Preview music and fonts from the CDN first; before export, both materialize locally, so rendering never depends on an unpredictable network."}</p></article></section>;
}

function Chip({ label }: { label: string }) { return <span className="rounded-md border border-white/10 bg-black/20 px-2 py-1 font-mono text-[9px] text-white/55">{label}</span>; }
function Pipeline({ active, label }: { active?: boolean; label: string }) { return <span className={`rounded-lg border px-3 py-3 text-center font-mono text-[9px] ${active ? "border-primary/35 bg-primary/[.1] text-primary" : "border-white/10 bg-black/20 text-white/55"}`}>{label}</span>; }
